-- MySQL Script generated by MySQL Workbench
-- Thu Sep  8 09:22:46 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema godb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema godb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `godb` DEFAULT CHARACTER SET utf8 ;
USE `godb` ;

-- -----------------------------------------------------
-- Table `godb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `date_create` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_update` DATETIME NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `godb`.`Favori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`Favori` (
  `id_fav` INT NOT NULL AUTO_INCREMENT,
  `long` VARCHAR(255) NOT NULL,
  `lat` VARCHAR(255) NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`id_fav`),
  INDEX `fk_Favori_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_Favori_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `godb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `godb` ;

-- -----------------------------------------------------
-- Placeholder table for view `godb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `godb`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `godb`.`view2` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `godb`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `godb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `godb`.`view1`;
USE `godb`;


-- -----------------------------------------------------
-- View `godb`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `godb`.`view2`;
USE `godb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
